#!/bin/bash
# Created: Sat Jul 27 2013 20:46:27 GMT+1000 (EST)

# Queue for the job:
#PBS -q batch

# The name of the job:
#PBS -N foobar

# Maximum number of CPU cores used by the job:
#PBS -l procs=10

# The amount of memory in gigabytes per process in the job:
#PBS -l pvmem=3gb

# Send yourself an email when the job (a)borts abnormally (b)egins (e)nds successfully
#PBS -m be

# The maximum running time of the job in days:hours:mins:secs
#PBS -l walltime=3:10:2

# Run the job from the directory where it was launched:
cd $PBS_O_WORKDIR

# The modules to load:
module load bwa-gcc/1.2.3

# The job command(s):
bwa some arguments
some other stuff

a bit more stuff
